import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { EffectorNext } from "@effector/next";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "./_components/theme-provider";
import { LayoutSelector } from "./_components/layout-selector";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	return (
		<html lang={locale} className={`${GeistSans.variable}`}>
			<body className="h-screen w-screen">
				<EffectorNext>
					<TRPCReactProvider>
						<ThemeProvider
							attribute="class"
							defaultTheme="system"
							enableSystem
							disableTransitionOnChange
						>
							<LayoutSelector>{children}</LayoutSelector>
						</ThemeProvider>
					</TRPCReactProvider>
				</EffectorNext>
			</body>
		</html>
	);
}
